project:
  type: website

author: CRhACKER7
  

website:
  title: "myQuartoProj-Bash"
  back-to-top-navigation: true

  repo-url: https://github.com/CrHacker7/MyQuartoProj-Bash
  repo-actions: [edit]
  repo-branch: master
  repo-link-target: '_blank'
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - myBashPage.qmd


  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    extensions:
      - mermaid